safe:        false
auto:        true
server:      false
server_port: 4242
baseurl:    /
exclude: Procfile, server.rb, Gemfile, Gemfile.lock, TODO

source:      .
destination: ./_site

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

